// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDicdGRcyxvoZjRnwewbMge7o66mrfU60',
    appId: '1:719704073477:web:23f2a48982f4c81ca3036c',
    messagingSenderId: '719704073477',
    projectId: 'quize-game-7278c',
    authDomain: 'quize-game-7278c.firebaseapp.com',
    storageBucket: 'quize-game-7278c.firebasestorage.app',
    measurementId: 'G-TEC06BX4N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkMvM9EDDlTMyGBxxW7XQgTa-b5ESdIo',
    appId: '1:719704073477:android:46fc4fe1cd880500a3036c',
    messagingSenderId: '719704073477',
    projectId: 'quize-game-7278c',
    storageBucket: 'quize-game-7278c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0AaZzkEzo7ZLVeWgzPpGbKH2dxTS8GYg',
    appId: '1:719704073477:ios:73075a56f93d1090a3036c',
    messagingSenderId: '719704073477',
    projectId: 'quize-game-7278c',
    storageBucket: 'quize-game-7278c.firebasestorage.app',
    iosBundleId: 'com.example.quizeler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0AaZzkEzo7ZLVeWgzPpGbKH2dxTS8GYg',
    appId: '1:719704073477:ios:73075a56f93d1090a3036c',
    messagingSenderId: '719704073477',
    projectId: 'quize-game-7278c',
    storageBucket: 'quize-game-7278c.firebasestorage.app',
    iosBundleId: 'com.example.quizeler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDicdGRcyxvoZjRnwewbMge7o66mrfU60',
    appId: '1:719704073477:web:213e7aead9753808a3036c',
    messagingSenderId: '719704073477',
    projectId: 'quize-game-7278c',
    authDomain: 'quize-game-7278c.firebaseapp.com',
    storageBucket: 'quize-game-7278c.firebasestorage.app',
    measurementId: 'G-ZD8R281J9W',
  );
}
